/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/algorithmtracker/backend/cmd/lib */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// InitDB initializes the database
//
extern char* InitDB(char* dbPath);

// AddProblem adds a new problem
//
extern char* AddProblem(char* jsonData);

// UpdateProblem updates an existing problem
//
extern char* UpdateProblem(char* jsonData);

// DeleteProblem deletes a problem by ID
//
extern char* DeleteProblem(int id);

// GetProblem retrieves a problem by ID
//
extern char* GetProblem(int id);

// GetProblems retrieves problems with optional filtering
//
extern char* GetProblems(char* filterJSON);

// AddTag adds a new tag
//
extern char* AddTag(char* name);

// GetTags retrieves all tags
//
extern char* GetTags();

// DeleteTag deletes a tag by ID
//
extern char* DeleteTag(int id);

// GetStatistics retrieves problem statistics
//
extern char* GetStatistics();

// ExportData exports data to file
//
extern char* ExportData(char* format, char* filePath);

// ImportData imports data from file
//
extern char* ImportData(char* format, char* filePath);

// BackupDatabase backs up the database
//
extern char* BackupDatabase(char* dbPath, char* backupPath);

// RestoreDatabase restores the database from backup
//
extern char* RestoreDatabase(char* dbPath, char* backupPath);

// FreeString frees a C string allocated by Go
//
extern void FreeString(char* str);

#ifdef __cplusplus
}
#endif
